### ISSUE TITLE
Post Processing of 15 minutes Eddy-Covariance Measurements

### ISSUE THREAD

**Issue by leilaher** [bgctw/REddyProc#4]
Hi all, my flux tower data has 15 minutes resolution, so I will work to modify my REddyProc copy. Suggestions to start? I´m new at R and learning as fast as possible. Thanks. Leila

**Comment by bgctw** [comment]
In principle the code should work for other equidistant time steps too (it does with hourly),
although several criteria on how many records should be present and the
window sizes would need to be adapted.

I recommend staring with the gapfilling and a user-given u* threshold.
You would need to adjust the window sizes and the quality flags, because different window sizes as specified by records translate to differnt window sizes by time.

**Comment by bgctw** [comment]
abandoned
